# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/lander/Source/Python/lab4_modelling/mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(381, 710)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.lineEdit_h = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_h.setFont(font)
        self.lineEdit_h.setObjectName("lineEdit_h")
        self.gridLayout.addWidget(self.lineEdit_h, 14, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.gridLayout.addWidget(self.label_19, 10, 3, 1, 1)
        self.lineEdit_alphaN = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_alphaN.setFont(font)
        self.lineEdit_alphaN.setObjectName("lineEdit_alphaN")
        self.gridLayout.addWidget(self.lineEdit_alphaN, 9, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 3, 0, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.gridLayout.addWidget(self.label_16, 14, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 6, 0, 1, 1)
        self.lineEdit_b2 = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_b2.setFont(font)
        self.lineEdit_b2.setObjectName("lineEdit_b2")
        self.gridLayout.addWidget(self.lineEdit_b2, 5, 2, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 5, 0, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.gridLayout.addWidget(self.label_24, 15, 3, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 10, 0, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.gridLayout.addWidget(self.label_18, 9, 3, 1, 1)
        self.lineEdit_t = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_t.setFont(font)
        self.lineEdit_t.setObjectName("lineEdit_t")
        self.gridLayout.addWidget(self.lineEdit_t, 15, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 8, 3, 1, 1)
        self.lineEdit_a1 = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_a1.setFont(font)
        self.lineEdit_a1.setObjectName("lineEdit_a1")
        self.gridLayout.addWidget(self.lineEdit_a1, 0, 2, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.gridLayout.addWidget(self.label_22, 13, 3, 1, 1)
        self.lineEdit_F0 = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_F0.setFont(font)
        self.lineEdit_F0.setObjectName("lineEdit_F0")
        self.gridLayout.addWidget(self.lineEdit_F0, 13, 2, 1, 1)
        self.set_def_button = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.set_def_button.setFont(font)
        self.set_def_button.setObjectName("set_def_button")
        self.gridLayout.addWidget(self.set_def_button, 16, 0, 1, 4)
        self.lineEdit_a2 = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_a2.setFont(font)
        self.lineEdit_a2.setObjectName("lineEdit_a2")
        self.gridLayout.addWidget(self.lineEdit_a2, 4, 2, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 8, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 4, 0, 1, 1)
        self.lineEdit_m1 = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_m1.setFont(font)
        self.lineEdit_m1.setObjectName("lineEdit_m1")
        self.gridLayout.addWidget(self.lineEdit_m1, 3, 2, 1, 1)
        self.lineEdit_l = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_l.setFont(font)
        self.lineEdit_l.setObjectName("lineEdit_l")
        self.gridLayout.addWidget(self.lineEdit_l, 10, 2, 1, 1)
        self.lineEdit_m2 = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_m2.setFont(font)
        self.lineEdit_m2.setObjectName("lineEdit_m2")
        self.gridLayout.addWidget(self.lineEdit_m2, 7, 2, 1, 1)
        self.lineEdit_R = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_R.setFont(font)
        self.lineEdit_R.setObjectName("lineEdit_R")
        self.gridLayout.addWidget(self.lineEdit_R, 12, 2, 1, 1)
        self.lineEdit_b1 = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_b1.setFont(font)
        self.lineEdit_b1.setObjectName("lineEdit_b1")
        self.gridLayout.addWidget(self.lineEdit_b1, 1, 2, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 12, 0, 1, 1)
        self.lineEdit_T0 = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_T0.setFont(font)
        self.lineEdit_T0.setObjectName("lineEdit_T0")
        self.gridLayout.addWidget(self.lineEdit_T0, 11, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.gridLayout.addWidget(self.label_17, 15, 0, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.gridLayout.addWidget(self.label_21, 12, 3, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 9, 0, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.gridLayout.addWidget(self.label_15, 13, 0, 1, 1)
        self.lineEdit_c2 = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_c2.setFont(font)
        self.lineEdit_c2.setObjectName("lineEdit_c2")
        self.gridLayout.addWidget(self.lineEdit_c2, 6, 2, 1, 1)
        self.lineEdit_c1 = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_c1.setFont(font)
        self.lineEdit_c1.setObjectName("lineEdit_c1")
        self.gridLayout.addWidget(self.lineEdit_c1, 2, 2, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 7, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 0, 1, 1)
        self.lineEdit_alpha0 = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_alpha0.setFont(font)
        self.lineEdit_alpha0.setObjectName("lineEdit_alpha0")
        self.gridLayout.addWidget(self.lineEdit_alpha0, 8, 2, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 11, 0, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.gridLayout.addWidget(self.label_20, 11, 3, 1, 1)
        self.run_button = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.run_button.setFont(font)
        self.run_button.setObjectName("run_button")
        self.gridLayout.addWidget(self.run_button, 17, 0, 1, 4)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 381, 20))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "a1"))
        self.label_19.setText(_translate("MainWindow", "см"))
        self.label_5.setText(_translate("MainWindow", "m1"))
        self.label_16.setText(_translate("MainWindow", "h"))
        self.label_8.setText(_translate("MainWindow", "c2"))
        self.label_7.setText(_translate("MainWindow", "b2"))
        self.label_24.setText(_translate("MainWindow", "с"))
        self.label_12.setText(_translate("MainWindow", "l"))
        self.label_18.setText(_translate("MainWindow", "Вт/см^2 К"))
        self.label_2.setText(_translate("MainWindow", "Вт/см^2 К"))
        self.label_22.setText(_translate("MainWindow", "Вт/см^2"))
        self.set_def_button.setText(_translate("MainWindow", "Set to default"))
        self.label_10.setText(_translate("MainWindow", "alpha0"))
        self.label_6.setText(_translate("MainWindow", "a2"))
        self.label_14.setText(_translate("MainWindow", "R"))
        self.label_3.setText(_translate("MainWindow", "c1"))
        self.label_17.setText(_translate("MainWindow", "t"))
        self.label_21.setText(_translate("MainWindow", "см"))
        self.label_11.setText(_translate("MainWindow", "alphaN"))
        self.label_15.setText(_translate("MainWindow", "F0"))
        self.label_9.setText(_translate("MainWindow", "m2"))
        self.label_4.setText(_translate("MainWindow", "b1"))
        self.label_13.setText(_translate("MainWindow", "T0"))
        self.label_20.setText(_translate("MainWindow", "К"))
        self.run_button.setText(_translate("MainWindow", "Run"))
